name: Main workflow to trigger other workflows
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main, triggered_workflow ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hey this worked"
  Trigger-Second-Workflow:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.MYPAT }}
      - run: |
          gh workflow run triggered-workflow