name: Main workflow to trigger other workflows
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main, triggered_workflow ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hey this worked"
  Trigger-Second-Workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          with:
            fetch-depth: 0
      - name: Trigger other owrkflow
        env:
          GH_TOKEN: ${{ secrets.MYPAT }}
        run: |
          gh workflow run triggered-workflow