name: Main workflow to trigger other workflows
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main, triggered_worfklow ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hey this worked"