name: Secondary workflow
run-name: ${{ github.actor }}

on:
  pull_request:
    types: [opened, edited]
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second workflow triggered"