name: Secondary workflow
run-name: ${{ github.actor }}

on:
  manual_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        default: 'production'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second workflow triggered"